### ISSUE TITLE
Make Easing Optional

### ISSUE THREAD

**Issue by Miserlou** [inorganik/countUp.js#1]
Easing doesn't look so good in some scenarios, maybe that should be toggleable?

**Comment by Miserlou** [comment]
I'm sorry for bumping this issue, but today I needed a way to animated a counter and found this library.

Turns out, judging by this issue, I already used this library 8 years ago for a project long since forgotten, but you've been here maintaining this library ever since. That's absolutely incredible maintainership, my good man. Incredible work, thank you very much!

**Comment by inorganik** [comment]
Cool! My pleasure.
