### ISSUE TITLE
update value with new duration

### ISSUE THREAD

**Issue by Jaskey** [inorganik/countUp.js#102]
Sometimes , we need to update the value though the numbers is still counting up, so `countup.update` is useful, but this method does not accept new options setting, as least, the new duration shoud be supported so that I can update the value with new duration like:
     
         demo.update(newValue,newDuration);

**Comment by inorganik** [comment]
feel free to submit a PR... in the meantime, why don't you just set the duration directly:
```
demo.duration = 2000; // new duration (2 secs)
demo.update(newValue);

**Comment by Jaskey** [comment]
Thank you, as a new user, since it is not demonstrated at the doc, I don't know these properties are public properties and can be set/update directly  like this way without public method,

 I will try. Thank you.
