### ISSUE TITLE
Error in digital generation

### ISSUE THREAD

**Issue by dang1314520** [inorganik/countUp.js#112]
Input 20054.44 change 20054.43

How to solve

**Comment by inorganik** [comment]
I assume what you mean is that you are setting 20054.44 as the `endVal`, but it is stopping at 20054.43? Testing this on the demo page, I can't reproduce using the default easing. However, if you use a custom easing function, it could cause this issue. Best to use the built in easing function, or fix whatever custom easing function you are passing in.

**Comment by inorganik** [comment]
Also, checkout the README, I just updated it so that it shows an example of how to smooth out animations for large numbers, like what you are trying to do.
