### ISSUE TITLE
16.4 * 100 != 1640

### ISSUE THREAD

**Issue by Gorden-Wang** [inorganik/countUp.js#113]
` self.frameVal = Math.floor(self.frameVal * self.dec) / self.dec;`

**Comment by inorganik** [comment]
What's the issue?

**Comment by Gorden-Wang** [comment]
One day , I use this below 
`var options = {
  useEasing : true, 
  useGrouping : true, 
  separator : ',', 
  decimal : '.', 
  prefix : '', 
  suffix : '' 
};
var demo = new CountUp("myTargetElement", 0, 16.4, 2, 2.5, options);
demo.start();`

it end with 16.39 。

**Comment by inorganik** [comment]
There was a bug introduced in 1.6.0 that caused this, but it is fixed now in 1.7.1.
