### ISSUE TITLE
Rounding issue

### ISSUE THREAD

**Issue by jackmcpickle** [inorganik/countUp.js#115]
Hi, are you able to investigate a rounding issue with some values. 

try `new CountUp("myTargetElement", 0, 37.66, 2, 1, options);` and `new CountUp("myTargetElement", 0, 37.30, 2, 1, options);` both finish 1 cent off.

Maybe countup needs to smash in at the end the actual value it was passed.

Thoughts?

**Comment by inorganik** [comment]
Thanks for reporting the issue, you found a bug! Looks like it was introduced in 1.6.1. I'll make a fix and tag a new release here in a bit.

**Comment by inorganik** [comment]
This is fixed in new version 1.7.1.

**Comment by jackmcpickle** [comment]
Awesome thanks. Also noted that you have 2 npm modules under different names? 

https://www.npmjs.com/package/countup
and 
https://www.npmjs.com/package/countup.js (new?)

not sure if you can delete one or and a depreciation notice?

**Comment by inorganik** [comment]
Yea, I will add a deprecation notice. Thanks.
