### ISSUE TITLE
Add AMD support

### ISSUE THREAD

**Issue by iplus26** [inorganik/countUp.js#118]
Hi,

I'm using `countUp.js` with RequireJS. I did a little work to use it as other dependencies like: 

    define(['countUp'], function(CountUp) { 
        new CountUp();
    });

Here is what I add below the original countUp codes. 

    if (typeof define === 'function' && define.amd) {
        define(function() { return CountUp; });
    }

Did I do things right? If it's okay, may I make a PR?

**Comment by KyleNeedham** [comment]
`countUp.js` already has AMD support use`dist/countUp.js`

**Comment by inorganik** [comment]
^^^
