### ISSUE TITLE
Design with Counter

### ISSUE THREAD

**Issue by sushant357** [inorganik/countUp.js#119]
Actually i want seperate block to per digit like a clock so i can give background to them. Can we do that ?

**Comment by inorganik** [comment]
You would need to just edit the `formatNumber` function. split the string it outputs and wrap each digit in a span, which you can style.

**Comment by sushant357** [comment]
Thanks Boss its done. Really thanks.

On Fri, Jun 3, 2016 at 8:22 PM, Jamie Perkins <notifications@github.com>
wrote:

> You would need to just edit the formatNumber function. split the string
> it outputs and wrap each digit in a span, which you can style.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/inorganik/countUp.js/issues/119#issuecomment-223600783>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE7SGFm8cdtRqeJGCPkzzi9b449T8Kr_ks5qID-wgaJpZM4ItXPV>
> .
>



-- 

*Thanks & Regards,*

*Sushant Jadhav*
*UI Developer*

**Comment by Skinwalker** [comment]
@sushant357 
if got the same problem - could you please share your code with us?
Thx
