### ISSUE TITLE
Character line 105

### ISSUE THREAD

**Issue by ucsdmath** [inorganik/countUp.js#121]
Character encoding issue line 105 in: countUp.js

JSC_PARSE_ERROR: Parse error. Character '¬' (U+00AC) is not a valid identifier start char at line 105 character 45
        else if (self.d.tagName === 'text' ||¬†self.d.tagName === 'tspan') {

**Comment by ucsdmath** [comment]
Just a space needed

**Comment by inorganik** [comment]
Thanks! Fixed.
