### ISSUE TITLE
Bower error - Missing file

### ISSUE THREAD

**Issue by clabnet** [inorganik/countUp.js#122]
On bower.json now the main node is:

`"main": "dist/countUp.min.js"`

to add also the countUpModule is correct to add also the file angular-countUp.js as is:

`"main": ["dist/countUp.min.js", "dist/angular-countUp.js"],`

It should be remove also bower.json (not .bower.json) or at least sync the two files.

**Comment by inorganik** [comment]
Can you please make a PR?

**Comment by inorganik** [comment]
pinging @clabnet ^^^

**Comment by inorganik** [comment]
hey there @clabnet, can you please make a PR?

**Comment by clabnet** [comment]
Ok Jamie, I have submitted my PR.

Thank's, bye

Claudio


Il 13/03/2017 23:54, Jamie Perkins ha scritto:

**Comment by inorganik** [comment]
Tante grazie @clabnet
