### ISSUE TITLE
how to set the value to a class not id

### ISSUE THREAD

**Issue by sanjshah** [inorganik/countUp.js#123]
Is it possible to set the value to a class id not an ID?

i.e. ".myClass"

**Comment by inorganik** [comment]
2 possible ways.
Using vanilla javascript:
```js
var arrayOfMatchedElements = document.getElementsByClassName('myClass');
```
Using jQuery: 
```js
var arrayOfMatchedElements = $('.myClass');
```
Either way gives you an array of matched elements. From here you can iterate over the array or just pick the first one:
```js
var target = arrayOfMatchedElements[0];
var numAnim = new CountUp(target, 24.02, 99.99);
```
