### ISSUE TITLE
Please mention exactly how to use this in your description

### ISSUE THREAD

**Issue by adityakrshnn** [inorganik/countUp.js#125]
I am not able to get an output even after including both countUp.js and angular-countUp.js and adding

h2 count-up end-val="873.4" (with cone brackets)

and 

h2 count-up id="numberAnimation" end-val="873.4" scroll-spy-event="elementFirstScrolledIntoView" scroll-spy

Please suggest!

**Comment by inorganik** [comment]
the **Usage** section in the README explains it very clearly. Did you debug? What do you see in the console?

**Comment by adityakrshnn** [comment]
This is what I got in console

Uncaught ReferenceError: angular is not defined
    at file:///D:/WT/project/js/angular-countUp.js:136:4

Please help

**Comment by inorganik** [comment]
`Angular is not defined` means just that. If you are not using Angular, you only need to include countUp.js, and nothing else. The only reason we also include angular-countUp.js is in case you are using Angular, which it appears you aren't.

**Comment by adityakrshnn** [comment]
I want to use scroll-spy-event="elementFirstScrolledIntoView", that requires angular-count-up.js right?

But even with regular countUp I can't see the counter.
what should I do?

**Comment by inorganik** [comment]
Scroll spy is a separate angular module. You need to create an angular app to use it. You need to read up that. There's plenty of docs for angular. 

Please don't create issues when you get stuck. Troubleshoot and debug yourself. Do some research. This isn't a help center.

**Comment by adityakrshnn** [comment]
Thank you for your help
