### ISSUE TITLE
Angular Example Page is a 404

### ISSUE THREAD

**Issue by pradt** [inorganik/countUp.js#126]
Hi just wanted to let you know that I'm receiving a 404 for the following link address : http://inorganik.github.io/Angular-scroll-spy

**Comment by inorganik** [comment]
Thanks for the heads up. The correct link is: http://inorganik.github.io/angular-scroll-spy/

Where did you get that link? I'm trying all my links and they seem to work fine...

**Comment by inorganik** [comment]
Found it. Incorrect link in the README. Thanks again.
