### ISSUE TITLE
Make decimals optional?

### ISSUE THREAD

**Issue by tmfksoft** [inorganik/countUp.js#131]
It'd be nice to have an option where decimals don't show on whole numbers on the end value.

Currently 10.5 shows as 10,
Adding decimal's would show 10.5 as intended but show 10.0 on a whole number.

Would it possible for you to add this in?

**Comment by inorganik** [comment]
It took me a moment to realize what you wanted - you want it to count like:

9.8
9.9
10
10.1
10.2
etc

I'd really rather not bloat the lib any more with additional options. But you can do it like this:

Inside the `formatNumber` function, replace this line: 
```
nStr = nStr.toFixed(self.decimals);
```

with this:
```
if (nStr % 1 > 0) {
    nStr = nStr.toFixed(self.decimals);
} 
```

**Comment by BenJackGill** [comment]
I am also looking for the same solution.

I tried searching for that line so that it could be replaced, but the code seems to have changed significantly since this was written.

Is there an updated version I can use?
