### ISSUE TITLE
Typescript declaration wasnt included in the NPM repo...

### ISSUE THREAD

**Issue by Milewski** [inorganik/countUp.js#132]
Missing typings from the npm.. which currently version is 1.7.1 which differs from the current repository on github...

**Comment by inorganik** [comment]
Thanks yes I need to update the npm package. npmjs seems to be down atm but I did tag a new release. Will try again later to update.

**Comment by Sparker73** [comment]
same here, github repo differs from the npm package

**Comment by unamix** [comment]
Please update the npm package

**Comment by ucsdmath** [comment]
I was going to post the same message.  It looks like today it is still at 1.7.1.  Thanks for the update for nom

**Comment by inorganik** [comment]
Sorry for the delay, it's updated now.
