### ISSUE TITLE
Countup whenever visible

### ISSUE THREAD

**Issue by jeffreydinh** [inorganik/countUp.js#135]
Is it possible to make all directives animate counting whenever going from visibility:hidden to visibility:visible?

**Comment by inorganik** [comment]
You'd have to use countUp in conjunction with a scroll-spy script. I wrote one for angular,  which can be integrated with the angular countUp directive included in this repo. [Here's a demo](http://inorganik.github.io/angular-scroll-spy/)

**Comment by jeffreydinh** [comment]
I'm sorry I forgot to mention not using scroll, the entire dashboard will be on one page and it is transitioning with visibility:hidden to visibility:visible. I've tried it with the angular-scroll-spy, but it doesn't work when the dashboard is not scrolling

**Comment by inorganik** [comment]
whatever hook you are using to change visibility, use that to call `start()` on your animation.

**Comment by jeffreydinh** [comment]
We are using the angular module version where we didn't have to use `start()` ?

**Comment by inorganik** [comment]
Maybe you have a $scope variable that causes the visibility to change? In that case, you can do an ng-if. When the DOM is created, the countUp will be constructed and will animate.
```
<h2 ng-if="thisIsVisible" count-up end-val="873.4"></h2>
```
