### ISSUE TITLE
is it possible to style the decimals ??

### ISSUE THREAD

**Issue by Salaboy** [inorganik/countUp.js#138]
I'm wondering if it is possible to apply a style only to the decimals so the look smaller than the main number. is that possible? can you recommend me a way to do that ?

**Comment by inorganik** [comment]
Edit this line of the `formatNumber()` function:

    x2 = x.length > 1 ? self.options.decimal + x[1] : '';

to look like this:

    x2 = x.length > 1 ? '<span>'+self.options.decimal+'</span>' + x[1] : '';

Now you have a `span` tag around your decimal and you can style it with CSS:

```css
#numAnim span {
    font-size:80%;
}
```
