### ISSUE TITLE
Add user defined function to define the result as you like

### ISSUE THREAD

**Issue by pslean** [inorganik/countUp.js#144]
#143

**Comment by inorganik** [comment]
@pslean, in #143 we discussed what you wanted to do and we resolved it: 

If you want a custom function to pass the result through, pass it in `options.formattingFn`. If you still want the result to be passed through the default formatting function, copy the formatting function code into your custom function that you pass to `options.formattingFn`. 

Also please don't open an issue that just references a closed issue.
