### ISSUE TITLE
Version Update 1.8.1 vs. 1.7.1 on website

### ISSUE THREAD

**Issue by ucsdmath** [inorganik/countUp.js#145]
Not sure if you intend different versions. But, bringing to your attention:

- npm (v1.8.1) : https://github.com/inorganik/countUp.js/releases
- Github (v1.8.1) : https://www.npmjs.com/package/countup.js
- Website (v1.7.1) : http://inorganik.github.io/countUp.js/

**Comment by inorganik** [comment]
Yea, just forgot to update the version number. Thanks.

**Comment by ucsdmath** [comment]
Great!  I do check for updates every so often.
