### ISSUE TITLE
Does not build with recent Angular 2 versions

### ISSUE THREAD

**Issue by lukaszsamson** [inorganik/countUp.js#154]
tested on Angular 2.4.9, typescript 2.0.10 with webpack JIT compile

**Comment by inorganik** [comment]
@vigie ?

**Comment by jculverwell** [comment]
I am getting this too.  Using the latest verison on the angular-cli I am getting this warning:

WARNING in ./~/countup.js/dist/countUp.module.js
15:24-31 Critical dependency: require function is used in a way in which dependencies cannot be staticall
y extracted

**Comment by jculverwell** [comment]
I suspect this maybe something to do with the Angular-CLI switching to AOT by default

**Comment by japalo** [comment]
Any ways of fixing this? I am having the same issue.
I am using angular-cli.

**Comment by vigie** [comment]
I'll try to have a look at the angular-cli use case this week. Other eyes on this also very welcome.

**Comment by hughred22** [comment]
I am having this issue as well. Please help to get this working again. Thanks!

**Comment by KevinBeckers** [comment]
Same issues

**Comment by inorganik** [comment]
hey community, can I get your help on this one? I do not use webpack currently on any projects. Can someone please troubleshoot this and make a fix, and then create a pull request? 

Seems like you'd be helping a lot of folks out.

**Comment by japalo** [comment]
Would very much love to, but i sadly lack the knowledge. If we do have white knight among us that can have a go at it and finds the solution i would very much appreciate to discuss what the solution is.

**Comment by alexreynier** [comment]
Has anyone figured this out by any chance? :-)

**Comment by zhaxi** [comment]
same issue

**Comment by inorganik** [comment]
@vigie :D

**Comment by yanai101** [comment]
same issue

**Comment by japalo** [comment]
@AndreasGassmann I ended up using a different package :(

**Comment by AndreasGassmann** [comment]
I'm using https://github.com/izupet/angular2-counto now, but it just doesn't look as nice as this package :(.

**Comment by inorganik** [comment]
Sorry to hear this issue hasn't been resolved yet. Has anyone actually tried to fix it? 

I've not yet dove into the world of Angular 2 and typescript. But if someone could please link me a zip of a sample project I could try to troubleshoot. I'm sure this is something simple... it just needs some attention.

**Comment by cbaxter713** [comment]
I'm having the same exact issue.  Any updates?

**Comment by brookstudio** [comment]
@cbaxter713 Same issue for me. But I make a not smart change on the countUp.module.ts just copy the code of declaration of CountUp from countUp.js into it and replace the "declare var CountUp". Now it work for me. here is the repo [https://github.com/brookstudio/countUp.js](https://github.com/brookstudio/countUp.js) and demo source here [https://github.com/brookstudio/countUpDemo](https://github.com/brookstudio/countUpDemo). check the demo here [https://github.com/brookstudio/countUpDemo](https://brookstudio.github.io/countUpDemo/)

**Comment by inorganik** [comment]
Hi all. Great news! **The Angular 2 module for CountUp.js has moved into [its own repo](https://github.com/inorganik/countUp.js-angular2) as of v1.9.0**. 

It has it's on npm package now as well, `countup.js-angular2`. 

Please make sure you update your projects, and please test to make sure I properly set it up. I'm not currently using angular ^2 so I have not tested yet. Feel free to make any PRs necessary over there and I'll merge them ASAP.

Closing this issue, as this repo no longer contains angular 2 files.

**Comment by jculverwell** [comment]
Thank you, much appreciated
