### ISSUE TITLE
Error below when I use requireJS and include jquery.waypoints.min.js before load jquery.counterup.js.

### ISSUE THREAD

**Issue by Amamatthew** [inorganik/countUp.js#157]
`jquery.counterup.js:86 Uncaught TypeError: $this.waypoint is not a function`
-------------------------------------------------------------------------------------
'jquery' version :"/lib/jquery/2.2.4/jquery.min"

**Comment by inorganik** [comment]
This lib includes a file called `countUp-jquery.js` and doesn't not include the file you stated. 

Also please remember Github issues aren't the place to run to whenever you have the slightest problem. You need to do some basic debugging.
