### ISSUE TITLE
Cannot disable grouping

### ISSUE THREAD

**Issue by myork** [inorganik/countUp.js#162]
It looks like recent changes broke the ability to disable grouping or to remove the separator.

When extending the default options with the passed options object the script iterates through each of the passed options and only updates the internal options if the following is true.

`options.hasOwnProperty(key) && options[key]`

The problem is that `options[key]` evaluates to false if useEasing or useGrouping is set to false, or if separator is set to ''.

**Comment by inorganik** [comment]
Yep, you are right. I'll make a fix. thanks

**Comment by myork** [comment]
Wow, that was an amazingly fast response. Thanks.

**Comment by inorganik** [comment]
haha you happened to catch me at a good time :)

**Comment by inorganik** [comment]
Fixed in v1.8.4.
