### ISSUE TITLE
TypeScript: TS7009: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.`

### ISSUE THREAD

**Issue by miracle2k** [inorganik/countUp.js#170]
`(115,29): error TS7009: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.`

I am getting this error when I do:

```
import Count from 'countup.js';

new Count(....)
```

TypeScript 2.3.2 with:

```
strictNullChecks": true,
"allowSyntheticDefaultImports": true,
"sourceMap": true,
"noImplicitAny": true,
```

**Comment by inorganik** [comment]
Closing this, since the Angular 2 module has moved into [its own repo](https://github.com/inorganik/countUp.js-angular2) as of v1.9.0. Please open any issues you have there.
