### ISSUE TITLE
request: define step value

### ISSUE THREAD

**Issue by codemonkeynorth** [inorganik/countUp.js#176]
Hi,

it would be useful to be able to supply a step number.... ie  to count to 10000 in 1000's

0
1000
2000 
etc

thanks
J

**Comment by inorganik** [comment]
This could be easily accomplished by passing a custom formatting function:
```js
var options = {
    formattingFn: function(num) {
        var result = Math.round(num / 1000) * 1000; // round to nearest 1000
        return result
    }
}

var demo = new CountUp("myTargetElement", 0, 10000, 0, 2.5, options);
demo.start()
```
http://jsfiddle.net/wgLyn1gg/

**Comment by codemonkeynorth** [comment]
ah great thanks
