### ISSUE TITLE
Angular requirement?

### ISSUE THREAD

**Issue by fjeddy** [inorganik/countUp.js#177]
When did Angular become a requirement for countUp?

`ReferenceError: Can't find variable: angular`

**Comment by inorganik** [comment]
You must be using bower eh? It's included in the bower file.... I have heard from at least one other person that they were getting it and didn't want it. I actually added it because someone requested it.  

Can you confirm if you installed via bower? If so I will just remove it from the bower file.

**Comment by fjeddy** [comment]
Yes sir, indeed using bower. It worked fine roughly a 6 months ago? when I installed it, updating it yesterday made my entire app stop functioning :/ Had to revert to the "old" version.

**Comment by inorganik** [comment]
I have moved angular modules (1 & 2) out of this repo and into their own repos as of v1.9.0. So this issue has been resolved.
