### ISSUE TITLE
can`t use SPACE symbol in separator option now

### ISSUE THREAD

**Issue by PrOpOvEdNiK** [inorganik/countUp.js#183]
because of
                       if (isNaN(self.options.separator)) {
				self.initialized = true;
				return true;
			}
			else {
				self.error = '[CountUp] separator cannot be a number: '+self.options.separator;
				return false;
			}

**Comment by inorganik** [comment]
Oi, `isNaN(' ')` equates to false. smh

**Comment by inorganik** [comment]
Fixed in 1.9.1.
