### ISSUE TITLE
Issue with `options.separator`

### ISSUE THREAD

**Issue by ucsdmath** [inorganik/countUp.js#184]
Hi Jamie,

This may be addressed with v1.9.0 in the section below, but differently.
Within the options I previously used with no separator, and in v1.9.0, it slightly broke for me:
  `
var options = {
    useEasing: true,
    useGrouping: true,
    separator: '',
    decimal: '',
    prefix: '',
    suffix: ''
};
`
I am now forced to use a comma in the separator when I like to use empty string (for no character).
If separator: '' , I can display 7452 (just numbers), however, now we are forced to use comma or some other character, and of course;  null works.
These work great:
- options.separator: '/'
- options.separator: '-'
- options.separator: '.'

But i would still like to use nothing (i.e., options.separator: '')
Is there a preferred way to define no separator?

Thank you,
Daryl

**Comment by ucsdmath** [comment]
Oh, and to add to my comment above, by assigning options.separator: null, we see the default is to use comma as the separator, and not defining separator at all also defaults with a comma as the separator (as you would expect).  Thank you!

**Comment by inorganik** [comment]
Hi Daryl, normally you could set `useGrouping: false` to use no separator. But I introduced a bug in 1.9.0 where I did an isNaN check on the separator. Surprisingly in javascript an empty string passed to `isNaN('')` equates to false. So I'll have to push a patch. Stay tuned.

**Comment by inorganik** [comment]
Fixed in 1.9.1

**Comment by ucsdmath** [comment]
Oh great!  Thank you for explaining about `useGrouping` and I realize I can also use v1.9.1 as previously used with options.useGrouping: true. Thank you!
