### ISSUE TITLE
Numbers are jagged or cut off on iOS 11

### ISSUE THREAD

**Issue by jacywang** [inorganik/countUp.js#188]
In our Ionic 1 and Angular 1 based Hybrid App, we use countUp.js to show the count up animation. All work well until iOS 11 came out very recently. The number is jagged or cut off in the animation. Anyone else is experiencing the same issue? 

Let me know if you need more information.

**Comment by inorganik** [comment]
Can you share a screenshot? 

I tested CountUp.js in Safari on iOS 11 on my iPhone and it looked fine.

**Comment by jacywang** [comment]
Thanks for looking into this, @inorganik! We just found out that this is due to a CSS attribute (transform) on our side. I'm going to close this.
