### ISSUE TITLE
Problem with including the angluar 2 component

### ISSUE THREAD

**Issue by isoftsolutions** [inorganik/countUp.js#193]
Hi @all,i have a problem to include the angular 2 Module in my ionic App.
can anybody help me?

i got the following error message:
Uncaught Error: Cannot find module "."     at webpackMissingModule (countUp.module.js:15)

Here are my relavant files:

**package.json:**
```
    "dependencies": {
...
"countup.js": "^1.9.3",
...
}
```

**app.module.ts:**

```
import {CountUpModule} from 'countup.js-angular2/dist/countUp.module';
@NgModule({
  declarations: [
 CountUpModule,
CounterComponent
.....
```

**CounterComponent**

```
@Component({
  selector: 'counter',
  templateUrl: 'counter.html'
})
export class CounterComponent {

  text: string;
  @Input() myStartVal: number = 5;
  @Input() myEndVal: number = 10;

  constructor() {
  }
}
```
**counter.html:**
```
<!-- Generated template for the CounterComponent component -->

  <h1 countUp="{useEasing: true}"
      [startVal]="myStartVal"
      [endVal]="myEndVal"
      [reanimateOnClick]="false"></h1>


```

anyone has an idea?
thank you so much
regards Stephan

**Comment by mikecabana** [comment]
Having the same issue

**Comment by inorganik** [comment]
Thank goodness @ALL does not ping everyone 🙂

Please report Angular issues in the [countUp Angular repo](https://github.com/inorganik/countUp.js-angular2). 

In your component, you need to `import * as CountUp from 'countup.js'`

As well, you need to include code to actually invoke CountUp. 

Again, see [countUp Angular repo](https://github.com/inorganik/countUp.js-angular2). That repo has some issues but I will be pushing a fix to it soon. The main gotcha is the way you need to import CountUp. I will close this issue when I push a fix there.

**Comment by mikecabana** [comment]
@inorganik In my case I installed CountUp via NPM. Does `import * as CountUp from 'countup.js'` still apply?

**Comment by inorganik** [comment]
Yes - installing via npm puts countUp in your node_modules folder. Run the install command with the `--save` option so that is listed as a dependency in your package.json, so the next person who downloads your repo and runs `npm install` will get it installed for them.

The import statement makes `CountUp` available to your component. The way modules work (node and es6) including a module in your bundle doesn't make globals, so you have to use `import` to get a reference to them.

**Comment by mikecabana** [comment]
@inorganik So does that mean the countup.js-angular-2 module is not needed. As it stands by reading this stream as well as the angualr repo, my understanding of what must be done to use this is: 
```
import {CountUpModule} from 'countup.js-angular2/dist/countUp.module';

@NgModule({
  declarations: [
 CountUpModule
...
```
AND in my component
```
import * as CountUp from 'countup.js';
...
let cu = new CountUp(...);
```
I'd like to use this as the angular repo intended as a directive as I find this kind of package useful.

**Comment by inorganik** [comment]
Hi all, I just pushed an update over here: https://github.com/inorganik/countUp.js-angular2

I tested and it's working great. Please see the README, it has all new instructions for usage.
