### ISSUE TITLE
Any way to delay the start of the count?

### ISSUE THREAD

**Issue by gigifrias** [inorganik/countUp.js#194]
```
[ ] Bug
[X] Feature request

CountUp.js version: v1.9.3

```

## Description

I'm currently using this along with a CSS animation which slides in the counter element. However, sometimes, the counter is already finished by the time the element slides into view. I was wondering if you had considered adding a delay parameter that would allow keep the counter from starting as soon as the document loads.

Thanks!

**Comment by inorganik** [comment]
This is something you can add pretty easily yourself:
```js
var numAnim = new CountUp("SomeElementYouWantToAnimate", 24.02, 99.99);
var myDelay = 1000;

setTimeout(function() {
    numAnim.start();
}, myDelay);
```

**Comment by gigifrias** [comment]
So I figured out this solution shortly after asking the question, thanks for responding nonetheless. Sorry for the silly question!
