### ISSUE TITLE
Move parameters to options object

### ISSUE THREAD

**Issue by jameslave** [inorganik/countUp.js#195]
```
[ ] Bug
[x] Feature request

CountUp.js version: 1.9.3
```

## Description
It was a bit strange seeing the countUp.js constructor accept 6 parameters. This is a well-known [code smell](https://sourcemaking.com/refactoring/smells/long-parameter-list) and contrasts with the majority of JavaScript libraries I've seen, which take only one or two parameters. I propose the parameters all be moved to a single options object, which would allow the following code:
```
const opts = {
  target: 'count-up',
  startVal: 24.02, 
  endVal: 99.99,
};

const animatedNumber = new CountUp(opts);
animatedNumber.start();
```
I could implement this and submit a pull request. Let me know if there's some good reason for the current implementation.

**Comment by inorganik** [comment]
There are only 3 required arguments currently, and even though the post you cited says "More than three or four parameters for a method" constitutes code small, that is not a good enough reason to introduce a major-breaking change.

It would cause a huge headache for not only people using the lib outright, but other libs/repos depending on it like the angularjs, angular and react libs (and more). They would all need to change. 

I agree non-required args should probably be refactored into the options arg, but the consequences are too great for such an arbitrary change.

**Comment by inorganik** [comment]
Would be cool to do a 2.0 release which removes the polyfil and is all es6. Would totally include this improvement in that...
