### ISSUE TITLE
OnTick method or specifying an interval?

### ISSUE THREAD

**Issue by kazoooka** [inorganik/countUp.js#200]
```
[ ] Bug
[ ] Feature request

CountUp.js version:

```
Hi,
i would like to ask if there is something like a tick method i could overwrite that specifies what will be done on each tick? 
Also is it possible to set a specific interval like 100ms for updating the numbers? I would need to let the numbers get updated only each 100ms or even 500ms...

**Comment by inorganik** [comment]
There isn't an animation callback, but I would suggest using `requestAnimationFrame()`, as CountUp does. If you are looking to do something at a specific interval like 100ms or 500s or an arbitrary value, use `setInterval`.
