### ISSUE TITLE
startVal is ignored on Firefox and Safari

### ISSUE THREAD

**Issue by ScottHarrisonDev** [inorganik/countUp.js#209]
```
[X] Bug
[ ] Feature request

CountUp.js version:
1.9.3
```

## Description
`startVal` seems to be ignored on Firefox and Safari (latest versions of both) as the counter starts from 0 in these browsers however it starts from the value that is set in the JS on chrome.

### Steps to reproduce
1. Create new CountUp instance with a `startVal` that is greater than 0. For example 200000000
2. View the counter in chrome to verify that is working correctly. It should start at 200000000.
3. View in Ffirefox/Safari and you should see the counter starting from 0 rather than the 200000000 it should be.

**Comment by inorganik** [comment]
Hmm, I couldn't reproduce. I ran the demo at http://inorganik.github.io/countUp.js/ on Safari and Firefox, with 200000000 as the start val and it worked fine. The demo creates a new instance every time you click "start". 

Just to make sure, in Firefox I copied from the code visualizer into the console:
```js
var demo = new CountUp('myTargetElement', 200000000, 5182, 0, 2.5, options);
```
As expected, it changed the startVal to 200000000. Then I did:
```js
demo.start();
```
And it worked fine.

Can you please copy all your js and html that is relevant to countUp and paste it here so I can see if anything else could be the issue? Likely your selector or how you are passing the values.

**Comment by ScottHarrisonDev** [comment]
Thanks for the prompt responses Jamie, looking into the code (We inherited the code and only have the minified JS so as you can imagine it's a bit of a slog!) I just found a line of code: `$("#contador").html((0).format()),` .... no idea why it was in there but that was almost certainly causing the issue which now is no longer a problem in FF or Safari.

Thanks again I'll close the issue 👍
