### ISSUE TITLE
define is not defined at countUp.js:12

### ISSUE THREAD

**Issue by ReeceKenney** [inorganik/countUp.js#212]
```
[ X ] Bug
[ ] Feature request

CountUp.js version:

```

## Description

Using the latest countUp.js, I see the error:
define is not defined at countUp.js:12

Line 12 of countUp.js:
`define(["require", "exports"], function (require, exports) {`

Thanks,

**Comment by inorganik** [comment]
It's the AMD module wrapping - how are you including CountUp in your project?

**Comment by mirkosantangelo** [comment]
Same error here. With a simple script embed from the CDN.

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

**Comment by inorganik** [comment]
@mirkosantangelo in CountUp 2.0, `CountUp` is no longer defined as a global. You can use requirejs and include your main script like this:
```
<script data-main="main.js" type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.1/require.min.js"></script>
```
and in your main script do:
```js
const CountUp = require('countup.js');
```
If it's easier for you to use it as a globally defined variable, pin your version to 1.9.3.

**Comment by inorganik** [comment]
**Update**: I experimented with multiple ways to include CountUp with all major module systems - UMD, AMD, and Commonjs and also tested different tools like Requirejs and Browserify. 

I settled on switching to a Commonjs module wrapping in 2.0.2 for two reasons:
1. Super compatible with Webpack
1. Super easy to bundle with Browserify if you don't want to deal with the complexity of Webpack

I also added a section on [Including CountUp](https://github.com/inorganik/countUp.js#including) in the README - it is quick and painless. I tested the steps on a test project and it was really quick and easy.  Hope this helps everyone.

**Comment by ReeceKenney** [comment]
Thanks for taking the time to follow up with this. 

I know these changes are for the better but I'm disappointed to see them. I teach programming to kids in my free time and what I liked about countUp was the ability to simply include the count up JS file and call the function. It was really quick and easy to teach and for the students to get their head around. 

I followed the steps in the 'including count up' section and I still had **a lot** of trouble getting it set up. I saw error after error that I eventually figured out but it was most definitely not quick or painless. Obviously this is due to my lack of knowledge but the process is now much more complicated and there's just no way I can use this in my teachings any longer. 

I honestly thank you so much for taking the time to respond here and resolve this issue so quickly though! :)

**Comment by inorganik** [comment]
Hey @ReeceKenney, change is hard, and I know updating CountUp has been a bumpy road. I've struggled with it quite a bit myself, having experimented with pretty much every module system, as well as brushing up on my typescript skills. Also, as I mentioned in another issue, I made a mistake in the "including CountUp section" where I forgot to add the `new` keyword in the example which caused a lot of people to have an error. 

However, I finally settled on the ES6 module wrapping in 2.0.4, and it really is super easy to implement (no build tools required!). But even better, it's future-proof- By the time the kids you are teaching are grown up it will be the standard everyone uses and knows. 

Despite all the headaches though, I think this repo is in a better place. Struggling through all these things - typescript, build systems, modules and tests - has helped me learn quite a bit, and I hope it can be an example for novice coders so they can see what a professionally-built project looks like.

**Comment by ReeceKenney** [comment]
I completely understand! I know these changes are definitely for the better. 

I do love the work you're doing here. Please keep it up!!

**Comment by BenJackGill** [comment]
I had same problem.

It's probably worth mentioning that not every has the same level of skill or understanding. I needed a quick solution but I had to spend the last 4 or 5 hours trying to figure this out.

I appreciate all the hard work going into this, and I tried my best to learn and make it work with JS modules as per the README but in the end I had to resort to using the 1.9.3 version.

My vote would be to make it work just like other scripts so that it's accessible to a wider audience - but that's just my two cents :)

Thanks for making this regardless!

**Comment by inorganik** [comment]
Good news all - CountUp is now also distributed as a UMD module and it exposes countUp as a global. You can use it like this when you include `countUp.umd.js` in a script tag:

```js
var numAnim = new countUp.CountUp('myTarget', 2000);
numAnim.start()
```
