### ISSUE TITLE
[Error] this.validateValue is not a function

### ISSUE THREAD

**Issue by cosecantt** [inorganik/countUp.js#214]
```
[ ] Error

CountUp.js version: ^2.0.3

```

## Description
```
var countUpModule = require('countup.js');
window.onload = function() {
    countUpModule.CountUp('reward', 2000).start();
}
```

Above code is in app.js bundled with webpack gives following error:

```
Uncaught TypeError: this.validateValue is not a function
    at Object.t [as CountUp] (countUp.min.js?1a23:1)
    at window.onload (app.js?6d40:29)
```

**Comment by inorganik** [comment]
Hmm, I tested the demo with the minified file and couldn't reproduce the error. Can you post your webpack config? I'm not sure what would cause this error.

**Comment by ejwaibel** [comment]
I'm seeing this exact same error when using it with Vue

**Comment by inorganik** [comment]
Couple things you could try - 

- use the [vue.js CountUp wrapper](https://github.com/xlsdg/vue-countup-v2) instead
- try installing `countup.js@2.0.0` (umd wrapper)
- try installing `countup.js@2.0.1` (amd wrapper)

2.0.2 and above have a commonjs wrapper. Let me know....

**Comment by melkishengue** [comment]
Getting the same error with webpack 3.4.1.

```
const countUpModule = require('countup.js');
const countUp = countUpModule.CountUp('count', 2000);
countUp.start();
```
 Uncaught TypeError: this.validateValue is not a function

**Comment by inorganik** [comment]
did anyone try the vue.js countup wrapper as previously suggested?

**Comment by Log1x** [comment]
Not using Vue, but I'm also getting this issue using webpack 4 (Laravel Mix 4).

**Comment by melkishengue** [comment]
@inorganik not using vue neither

**Comment by inorganik** [comment]
Can everyone on this thread please give me details on your build? Webpack config, and any other relevant info. If I can't reproduce the error I can't fix it. Thanks

**Comment by Log1x** [comment]
https://log1x.com/files/countup.js-example.zip

```
yarn install && yarn run build
```

**Comment by inorganik** [comment]
Oh boy. Well big time facepalm guys. 😂 I forgot to put the `new` in example usage. This fixes it:

```js
window.onload = function () {
  var countUp = new countUpModule.CountUp('countup', 2000);
  countUp.start();
}
```
Sorry about that. @Log1x thank you for the code, it helped me discover the error. FYI with yarn you can do `yarn && yarn build`. Also I updated the README.

**Comment by inorganik** [comment]
FYI, if you upgrade to 2.0.4, it's now an ES6 module. Then it's simply:
```js
import { CountUp } from 'countup.js';

var countUp = new CountUp('countup', 2000);
```
If you want to stick with commonjs, you can lock in at v2.0.3.
