### ISSUE TITLE
[Bug] SyntaxError: export declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by s1monj** [inorganik/countUp.js#219]
CountUp.js version: 2.0.4
Firefox version: 60.3

## Description

This [line](https://github.com/inorganik/countUp.js/blob/29ba37c1f4f02a00ef19c9abbdc58d1b610f7d38/dist/countUp.js#L248)
```
export { CountUp };
```
is giving the error
```
SyntaxError: export declarations may only appear at top level of a module
```
After downloading countup with npm, copying it to my vendor directory and including it in my rails asset pipeline. I have other packages installed the same way without any issues.

**Comment by inorganik** [comment]
What is outputting this error? The browser? Rails? Is rails bundling your app?

**Comment by s1monj** [comment]
The browser console is displaying the error on load.

I'm in development mode so rails is including the dist/countUp.js source as a separate file in the html head:
```
<script src="/assets/countUp.self-9681bf093b19afe625c875823bc2c8f0546aa566d84c74e0ab7513420f06e5c0.js?body=1"></script>
```
I realise now it's probably an issue with Rails and ES6 modules, so I'll work that out first.

**Comment by inorganik** [comment]
Let us know what you find out. The distributed js is generated by typescript with the module set to `esnext`. I've found ES6 modules to be the most widely compatible. You might try upgrading Ruby and/or your bundler. 

As an alternative, In the README I list previous versions which are packaged with different modules: 

- UMD - `npm i countup.js@2.0.0`.
- AMD -`npm i countup.js@2.0.1`.
- commonjs - `npm i countup@2.0.3`.
