### ISSUE TITLE
this.pauseResume()  Bug

### ISSUE THREAD

**Issue by weishax** [inorganik/countUp.js#220]
```
CountUp.js version: 1.8.2
```

## Description
"endVal" is complete.
"endVal" cannot be updated again with this. update () while this. pauseResume () is triggered twice.

![image](https://user-images.githubusercontent.com/40553114/57181487-0270b980-6ec7-11e9-9620-a0071c17dc4b.png)

**Comment by inorganik** [comment]
Please update to the latest version and your issue will be solved. :)
