### ISSUE TITLE
Auto run when content is shown?

### ISSUE THREAD

**Issue by louiemiranda** [inorganik/countUp.js#227]
```
[ x ] Question
CountUp.js version: 2.0.4

```

## Description

I was able to integrate it to an angular app, using the following repo/guide --https://github.com/inorganik/countUp.js-angular2.

Just curious if on page-load and when content is shown, can it automatically run? Instead of clicking it?

Thanks

**Comment by inorganik** [comment]
Yep, just make sure the endVal is set in your component
