### ISSUE TITLE
Can't import as ES6 module - where is 2.0.4?

### ISSUE THREAD

**Issue by ArianeNubee** [inorganik/countUp.js#228]
```
[?] Bug
[ ] Feature request

CountUp.js version: 2.0.3

```

## Description

I found this issue : https://github.com/inorganik/countUp.js/issues/215

Like that person, I'm unable to import CountUp in my ES6 setup, since:

> Non-existent export 'CountUp' is imported from ../../../../../../node_modules/countup/dist/countUp.min.js

I import it this way :
```javascript
import { CountUp } from 'countup';
```

In the issue I linked, you said that you released 2.0.4 as an ES6 export and apparently that fixed everything. Where is that version though? It seems the latest release is 2.0.3.

My bundler is [CodeKit](https://codekitapp.com/) 3.9.2. It offers several ES6 bundling options :
![Capture d’écran, le 2019-08-02 à 09 22 04](https://user-images.githubusercontent.com/19208414/62373074-08e2f180-b507-11e9-8d1d-5dc749e8f80e.png)

None of these change anything, though. They all can't find 'CountUp'. Help.

**Comment by inorganik** [comment]
CountUp has been at 2.0.4 since March 2019. However on the [releases](https://github.com/inorganik/countUp.js/releases) page I didn't draft a release until now. That wouldn't matter for you though if you installed the latest version from npm.

```
npm i countup.js@latest
```

Will give you the latest version which is exported as an ES6 module.

**Comment by ArianeNubee** [comment]
Ooooh. I was installing `countup`, not `countup.js` in Yarn. Slight mistake makes a big difference. Thanks a bunch.

By the way, my bundler says this about countUp:

> Bundled and transpiled successfully, but with warnings: The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten

It still works though. I don't know if this is relevant information to you.

**Comment by inorganik** [comment]
Thanks. I have not seen that, but I'll look into it.
