### ISSUE TITLE
How to use the counted up value in e.g. a function

### ISSUE THREAD

**Issue by derbalint** [inorganik/countUp.js#229]
```
[ ] Bug
[x ] Feature request

CountUp.js version: 2.0.4

```

## Description

Everything works great, thanks for this!
But how can I display/store the numbers/value that are counted up somewhere else than in an element with an id. For example I would like to have a 

let x = counter;

so that i can work with x in another function.
I tried to get the values out of an input with oninput and onchange but they don't work as the values are changed via countUp.js and not by a user.

Any help on that?

**Comment by inorganik** [comment]
I'm not sure I understand completely, sounds like you want the frame-by-frame values as it's counting, is that right?

**Comment by derbalint** [comment]
Hey, thanks for your answer! Yes exactly, and save them in a let or var for further use.

I found a solution using MutationObserver and adding the className="observable" to the div where the textContent is being counted up by countup.js

This works, but if you have a better/faster solution I would be very happy to see/lern it (:

`var composeObserver = new MutationObserver(function(mutations){ 
            mutations.forEach(function(mutation){
               let hoursCount = mutation.addedNodes[0].textContent;
               console.log(hoursCount);
            });
        });
    
        function addObserverIfDesiredNodeAvailable() {
            var composeBox = document.querySelector(".observable");
            if(!composeBox) {
                //The node we need does not exist yet.
                //Wait 500ms and try again
                window.setTimeout(addObserverIfDesiredNodeAvailable,1);
                return;
            }
            var config = {characterData:true, subtree: true, childList: true};
            composeObserver.observe(composeBox,config);
        }
        addObserverIfDesiredNodeAvailable();`

**Comment by inorganik** [comment]
You can access the `frameVal` property:
```js
    const demo = new CountUp('myTargetElement', endVal, options);
    setInterval(() => {
      console.log('frameVal', demo.frameVal)
    }, 300);
```
which would output something like
```
frameVal 305
frameVal 1245
frameVal 2287
```
If you want to be notified _every time_ the value changes, pass a custom formatting function, because you can use it like a frame-by-frame callback:
```js
const format = (num) => {
  // do something with num
  return num + ''; // return string, this gets printed in the DOM
}
const options = { formattingFn: format }
demo = new CountUp('myTargetElement', endVal, options);
```
Hope that helps

**Comment by derbalint** [comment]
Thank you so much! Thats absolutely perfect and saves me the whole MutationObserver.
CountUp.js is a really great class, thank you for that!
