### ISSUE TITLE
counts up, and then counts down to zero, not sure why

### ISSUE THREAD

**Issue by 1blockologist** [inorganik/countUp.js#231]
```
[x] Bug
[ ] Feature request

CountUp.js version: 2.0.4

```

## Description

Updated this + vue-countdown-v2 to 4.0.0 and now my counters count up and then down to zero. (prior versions no longer worked at all after updating some different dependencies, not sure which)

you can check out the current version of https://pareto.network/leaderboards to see this failing in action

It is supposed to only count up

my main hunch is that there are no longer multiple instances of the object and that one counter (which does count down) is overriding all of the others.

**Comment by inorganik** [comment]
How are you using it? - show us code. CountUp still supports multiple instances.

**Comment by 1blockologist** [comment]
@inorganik I found a fix for my purposes in a vue-countup-v2 configuration file.

https://github.com/xlsdg/vue-countup-v2/issues/22

I'm not sure if the behavioral change was from updating this library, the vue library, or vue itself or a npm or any other dependency.
