### ISSUE TITLE
Can provide an updated options method？

### ISSUE THREAD

**Issue by sakura-flutter** [inorganik/countUp.js#237]
```
[ ] Bug
[ ] Feature request

CountUp.js version:
2.0.5
```

## Description

Google Translate：
I want to change from 10(decimalPlaces: 0, because i don't want to show 10.00) to 11.02(decimalPlaces: 2)
but there is no way to do it

**Comment by inorganik** [comment]
Like this: https://jsfiddle.net/vhLs9gpu/

**Comment by sakura-flutter** [comment]
> 像这样？https://jsfiddle.net/vhLs9gpu/

Google Translate：
emm，
I have tried to do this, but it will start from 0, I hope it can start from the last number, like update the end value。

**Comment by inorganik** [comment]
`startVal` is also an option: https://jsfiddle.net/3sxwprht/

**Comment by sakura-flutter** [comment]
> `startVal` is also an option: https://jsfiddle.net/3sxwprht/

thank~
this solved my problem
