### ISSUE TITLE
countUp-jquery.js does not use the API correctly

### ISSUE THREAD

**Issue by teej** [inorganik/countUp.js#242]
```
[X] Bug
[ ] Feature request

CountUp.js version:
HEAD
```

## Description
In `countUp-jquery.js`, there's a "defaults" object -

```
    var defaults = {
      startVal: 0,
      decimalPlaces: 0,
      duration: 2,
    };
```
which specifies a set of default options, but they're completely thrown away, since the countup API is called as so:
```
var countUp = new CountUp(elem, defaults.endVal, defaults.options);
```

**Comment by inorganik** [comment]
Thank you, I updated the gist.
