### ISSUE TITLE
Failed to import package as module

### ISSUE THREAD

**Issue by LukasVaculcik** [inorganik/countUp.js#243]
[X] Bug
[ ] Feature request

CountUp.js version: 2.0.6

## Description

Hello, I installed the package with NPM and then trying to include it as a module into my scripts with

`import { CountUp } from 'countup.js'`

but I get ParseError: 'import' and 'export' may appear only with 'sourceType: module'

I get the same error when I try to include the package with exact path to the script file:
`import { CountUp } from '../../../node_modules/countup.js/dist/countUp.min.js'`

I compile scripts with babel.

Could you please help me solve this issue? I have no idea what could be wrong, I can include other ES6 script modules with no problem.

**Comment by inorganik** [comment]
Do you have `type="module"` in the script tag that includes your script that imports countUp? Could you also post more info about your setup?

**Comment by LukasVaculcik** [comment]
That's it, I didnt mark final compiled script as "module". Thank you for answer.
