### ISSUE TITLE
starts counting and then vanishes

### ISSUE THREAD

**Issue by Ic3m4n34** [inorganik/countUp.js#244]
```
[x] Bug
[ ] Feature request

CountUp.js version:
2.0.6
```

## Description

Here is a reproduction link: https://codesandbox.io/s/ecstatic-knuth-mmwmj?file=/index.html

When you refesh the page, it starts counting up for a second or so and then vanishes

**Comment by Ic3m4n34** [comment]
I was trying to avoid importing the countup.js file. I guess that doesn't work. I've changed my approach now and went your way. Thank you 😊

**Comment by inorganik** [comment]
You can, if you use the included countUp.umd.js - it exposes `countUp` as a global variable. In this repo, index.html has fallbacks for browsers that don't support es6 modules:

```html
<script nomodule src="dist/countUp.umd.js"></script>
<script nomodule src="demo/demo-nomodule.js"></script>
```

Then you can invoke countUp like this:
```js
var demo = new countUp.CountUp('myTargetElement', 100);
```

For whatever reason I couldn't get it to work on codesandbox, but if you have cloned this repo, comment out the module import in index.html, and remove the "nomodule" attribute on the other script tags. Then run `npm i` and `npm run serve` and you can see it work.
