### ISSUE TITLE
Value is not updated correctly when navigating quickly to value

### ISSUE THREAD

**Issue by burnaDLX** [inorganik/countUp.js#245]
```
[x] Bug
[ ] Feature request

CountUp.js version: 2.0.6
```

## Description
![countup_bug_minimal_example](https://user-images.githubusercontent.com/12218103/91055172-9880a400-e624-11ea-9dcd-37f3c75cf4fc.gif)

If you quickly navigate between to values (e.g. radio-buttons via arrow keys) the value is not updated correctly even though the passed value is correct (see console.log in the minimal example).

[Link to minimal example](https://stackblitz.com/edit/minimal-countup?file=index.js)

**Steps to reproduce:** Navigate to the value "100.000" by pressing the right arrow key twice very fast.
**Actual behavior:** The counter increments to "10,000".
**Expected behavior:** The counter increments to "100,000".

**Comment by inorganik** [comment]
thanks, I think I have a fix: https://stackblitz.com/edit/countup-typescript-dvetau?file=countUp.ts

**Comment by burnaDLX** [comment]
Can confirm, would work for me.

**Comment by burnaDLX** [comment]
@inorganik Will you release a version with the bugfix? Should I leave this ticket open until then?

**Comment by inorganik** [comment]
Just cut a release. This is fixed in v2.0.7
