### ISSUE TITLE
duration 设置成0会显示NaN

### ISSUE THREAD

**Issue by izhaoqing** [inorganik/countUp.js#250]
```
[v] Bug
[ ] Feature request

CountUp.js version: 2.0.7

```

## Description

duration 设置成0，调用 update 方法会显示NaN

```js
const options = {
  duration: 0,
};
let demo = new CountUp('myTargetElement', 623, options);
if (!demo.error) {
  demo.start();
} else {
  console.error(demo.error);
}
demo.update(700);

```

**Comment by 8BitJonny** [comment]
First I didn't understand the title of the issue because I don't speak Chinese. But yes, I also just ran into this issue
:+1:

**Comment by inorganik** [comment]
Curious why would you set a 0 duration?

**Comment by 8BitJonny** [comment]
It was my initial thought on how to have 0 animation when the number is being initialised and then only have animation when number changes away from the initial state.

Then I found that my initial understanding of `startVal` was wrong and that it serves exactly this purpose.
Initially I thought, `startVal` was the starting value of EACH animation and not just the initial one. 

And yeah, through that I encountered this `Nan` behaviour

**Comment by inorganik** [comment]
Closing since I don't think setting duration to zero is a valid use case

**Comment by jhxxs** [comment]
I get this too, eventually I set `duration: 0.001`，and everything works fine.

**Comment by macjjuni** [comment]
To set it up the way you want, do this
Make the `start` and `end` values the same and set the `duration` value to 0.
