### ISSUE TITLE
decimals property ignored

### ISSUE THREAD

**Issue by cdecinkoKnight** [inorganik/countUp.js#256]
```
[ x] Bug
[ ] Feature request

CountUp.js version:  2.0.7

```

## Description

Unable to specify the number of decimal places. countUp.js always rounds off the value to the nearest whole number.

        <ICountUp
          v-if="value > 0"
          :startVal="0"
          :endVal="value"
          decimals="3"
          :duration="duration"
          :options="{
            useEasing: true,
            useGrouping: true,
            separator: ',',
            decimal: '.',
            prefix: '',
          }"
          @ready="onCountReady"
        />
        <span v-else>0</span>

**Comment by inorganik** [comment]
Looks like you meant to file this issue in the [Vue CountUp repo](https://github.com/xlsdg/vue-countup-v2)
