### ISSUE TITLE
Start counting when item is on screen

### ISSUE THREAD

**Issue by woutr-nl** [inorganik/countUp.js#270]
```
[ ] Bug
[X] Feature request / Question

CountUp.js version:
2.0.8
```

## Description

I'm using CountUp right now, and it starts when the page is loaded. I want to be able to start the count when it's on the users view/viewport.

**Comment by inorganik** [comment]
You can do this with a [scroll spy](https://getbootstrap.com/docs/5.1/components/scrollspy/)... but wouldn't be a bad feature to build into the lib.

**Comment by woutr-nl** [comment]
Hi Inorganik,

Awesome to hear. I've been playing around with scroll spy now.. but can't seem to get it working. Not that experienced with JS.. whoops. Do you have any idea when you are going to implement it?

**Comment by woutr-nl** [comment]
Hi @inorganik 

Any update? :)

**Comment by inorganik** [comment]
Ok I have something.... [check it out](https://countup-typescript-fvvc8n.stackblitz.io). I'll put up a PR later this morning.

**Comment by woutr-nl** [comment]
That's exactly what i need haha!
