### ISSUE TITLE
Javascript not seems to execute

### ISSUE THREAD

**Issue by woutr-nl** [inorganik/countUp.js#276]
[X] Bug
[ ] Feature request

CountUp.js version:

2.1.0

## Description

I think that i'm being a moron again, but i'm just going to ask it.
I've implemented CountUp in my Wordpress with an Code Snippet;

```
add_action('wp_head', 'CountUp');
function CountUp(){
?>
<head>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/countup.js/2.1.0/countUp.min.js" type="module"></script>
</head>
<?php
};
```

Within my Wordpress page (using Oxygen Builder) i'm trying to run the code below;

```
window.onload = function() {
  var options = {
    useEasing : true, 
    useGrouping : true, 
    separator : ',', 
    decimal : '.', 
    prefix: '',
	enableScrollSpy: true,
  };
  var demo = new CountUp("number1", 0, 300, 0, 2.5, options);
  demo.start();
}
```

When i save and go to the page, the error log tells me this; 

```
Uncaught ReferenceError: CountUp is not defined
    at window.onload ((index):138:14)
```

And i just can't seem to find out what is causing this problem. Can you help me out with this maybe?

**Comment by inorganik** [comment]
Several things - first, for the way you included Countup, the script that invokes CountUp needs to be included as a module and CountUp needs to be imported. Second, your method signature is very outdated. Read the README to learn how to use CountUp. You might also consider using the wordpress plugin (also linked from the README).
