### ISSUE TITLE
i develop a vue3 component wrap for countUp.js , welcome the usage

### ISSUE THREAD

**Issue by jizai1125** [inorganik/countUp.js#277]
https://github.com/jizai1125/vue-countup-v3

**Comment by inorganik** [comment]
Did you know there was already a Vue wrapper for CountUp? It is linked from the README. https://github.com/xlsdg/vue-countup-v2

I believe the "v2" in the package name is referring to CountUp, but its package.json installs the latest of both vue and countup.

**Comment by jizai1125** [comment]
Hahaha, my English is not good. It's all right. I just saw it, but I wrote Vue JS version 3 grammar, as a practice, can also be used by people in need, thank you
------------------&nbsp;原始邮件&nbsp;------------
发件人:                                                                                                                        "inorganik/countUp.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月11日(星期五) 晚上8:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [inorganik/countUp.js] i develop a vue3 component wrap for countUp.js , welcome the usage (Issue #277)





 
Did you know there was already a Vue wrapper for CountUp? It is linked from the README. https://github.com/xlsdg/vue-countup-v2
 
I believe the "v2" in the package name is referring to CountUp, but its package.json installs the latest of both vue and countup.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by inorganik** [comment]
Thanks for you contribution!
