### ISSUE TITLE
How to use countUP - Jquery with a class selector and values from data attribute?

### ISSUE THREAD

**Issue by krishnaprasadkckp** [inorganik/countUp.js#283]
## Description

Thanks for the great plugin. 
I'm trying to use the Jquery version with a general format everywhere on my website, like this -  
`<span class="counter"  data-number="96" data-decimal-count="0"></span>`
As per documentation, it seems a unique ID with numbers. Can I use like this with this plugin?

**Comment by barkdoll** [comment]
I'm not a project contributor, but you can try this:
```js
$('.counter').each(function() {
  $(this).countup({ ...this.dataset });
});
```
