### ISSUE TITLE
'useGrouping' setting ignored on dynamically created countup

### ISSUE THREAD

**Issue by despecial** [inorganik/countUp.js#284]
```
[X] Bug
[ ] Feature request

CountUp.js version: 2.2.0

```

## Description

Case: multiple instances created within an observer ('enableScrollSpy' was not compatible with another script).
Grouping is by default active and that's fine, except for 1 number, it needs to be disabled. The dynamic settings come from data-attributes and work fine so far. But only the **'useGrouping'** setting is ignored. Tested: disabling grouping by default - works.

```
let countups = {};
let timeouts = {};
const counters = document.querySelectorAll(".number-item");
const countersObserver = new IntersectionObserver (function (entries, observer) {
	var i = 0;
	entries.forEach(function(entry) {
		if (entry.isIntersecting) {
			var	cid = entry.target.id
				cno = entry.target.dataset.number,
				suf = entry.target.dataset.suffix || "",
				time = entry.target.dataset.time || "2",
				sep = entry.target.dataset.sep || ".",
				grp = entry.target.dataset.group || true,
				opts = {
				'enableScrollSpy': false,
				'suffix': suf,
				'duration': time,
				'separator': sep,
				'useGrouping': grp
			}
			countups[entry.target.id]= new countUp.CountUp(cid, cno, opts );
			timeouts[entry.target.id] = setTimeout(() => {
				countups[entry.target.id].start();
			}, 0 + (500*i) );
			observer.unobserve(entry.target);
		}
		i++;
	},{});
});
counters.forEach ( function (countUpItems) {
	countersObserver.observe(countUpItems);
});
```

**Comment by inorganik** [comment]
What are the specific options are you setting for the instance where useGrouping seems to be ignored?

**Comment by despecial** [comment]
```<span class="item-count" id="counter7" data-number="2021" data-sep="" data-group="false"></span>```

**Comment by inorganik** [comment]
CountUp doesn't have any attribute reading abilities. How are you passing these options in javascript/typescript?

**Comment by despecial** [comment]
Please check the first post. I get the values via the event target and set the options to create the counter

**Comment by inorganik** [comment]
Ok so I see this:
```
grp = entry.target.dataset.group || true,
```
The value of the attribute is string`"false"` and I don't know if that's coerced into a boolean or not. But even if it was you are doing `grp = false || true` which will set it to true.

Last, you are supposedly setting an empty separator, and CountUp will set useGrouping to false given an empty separator. So I don't understand how you are interpreting that it is ignoring useGrouping when you've passed an empty separator?

**Comment by despecial** [comment]
A the last info was helpful. The check failed on the empy separator.
Fixed it with: `sep = (entry.target.dataset.sep==="") ? "" : ".",`
Removed the grouping data attribute and now it works as intended. Thanks!

Btw: countUp is awesome with data-attributes and many instances.
