### ISSUE TITLE
Count down is slower than count up when end is 0

### ISSUE THREAD

**Issue by ryancrunchi** [inorganik/countUp.js#287]
```
[x] Bug
[ ] Feature request

CountUp.js version: 2.3.1
```

## Description

When the value goes from 0 to 7240 the duration is respected
When the value goes from 7240 to 0 the animation seems longer
When the value goes from 7240 to 1 the duration is respected

You can easily try in home page
Start `0`, end `7240`, duration `5`, the duration is really 5 seconds
Start `7240`, end `0`, duration `5`, the actual duration seems more 7s (40% longer)
Start `7240`, end `1`, duration `5`, the duration is really 5 seconds
https://inorganik.github.io/countUp.js/

I can also view this difference in my production app with lower duration (0.5s when going up is 0.7s when going down) which makes my animations not synced.

**Comment by inorganik** [comment]
After some debugging, I found there's an issue with `determineDirectionAndSmartEasing()`, which is not halving duration as it should (only when counting down) when the second half of the animation runs. Smart easing breaks up the animation into 2 parts with equal durations but a smaller number in the second half so easing is visible. 

So what's happening is the first half is half the set duration, but the second half is full duration meaning the animation is 150% as long as it should be. I will work on a fix.

**Comment by inorganik** [comment]
Fixed in v2.3.2
