### ISSUE TITLE
Cannot read properties of null (reading 'tagName')

### ISSUE THREAD

**Issue by AstRonin** [inorganik/countUp.js#293]
[x] Bug
[ ] Feature request

CountUp.js version:

`"version": "2.3.2",`

`"react-countup": "^6.3.2",`
`"react": "18.2.0",`

## Description

I use react. As I understand instance `this.el` deleted before called reset.

**I'm not sure this bug related to this library. Maybe it should redirect to [react-countup](https://github.com/glennreyes/react-countup) library"**

@glennreyes Could you please look to this ticket

```
Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'tagName')

Call Stack
t.printValue
node_modules/countup.js/dist/countUp.min.js (1:4846)
t.reset
node_modules/countup.js/dist/countUp.min.js (1:4275)
eval
node_modules/react-countup/build/index.js (251:0)
eval
node_modules/react-countup/build/index.js (134:0)
eval
node_modules/react-countup/build/index.js (289:0)
safelyCallDestroy
node_modules/react-dom/cjs/react-dom.development.js (22932:0)
commitHookEffectListUnmount
node_modules/react-dom/cjs/react-dom.development.js (23100:0)
commitPassiveUnmountInsideDeletedTreeOnFiber
node_modules/react-dom/cjs/react-dom.development.js (25098:0)
commitPassiveUnmountEffectsInsideOfDeletedTree_begin
node_modules/react-dom/cjs/react-dom.development.js (25048:0)
commitPassiveUnmountEffects_begin
node_modules/react-dom/cjs/react-dom.development.js (24956:0)
commitPassiveUnmountEffects
node_modules/react-dom/cjs/react-dom.development.js (24941:0)
flushPassiveEffectsImpl
node_modules/react-dom/cjs/react-dom.development.js (27038:0)
flushPassiveEffects
node_modules/react-dom/cjs/react-dom.development.js (26984:0)
performSyncWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (26076:0)
flushSyncCallbacks
node_modules/react-dom/cjs/react-dom.development.js (12042:0)
commitRootImpl
node_modules/react-dom/cjs/react-dom.development.js (26959:0)
commitRoot
node_modules/react-dom/cjs/react-dom.development.js (26682:0)
finishConcurrentRender
node_modules/react-dom/cjs/react-dom.development.js (25981:0)
performConcurrentWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (25809:0)
workLoop
node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js (239:0)
MessagePort.performWorkUntilDeadline
node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js (533:0)
```

**Comment by inorganik** [comment]
You need to file this in the [react-countup](https://github.com/glennreyes/react-countup) repo. But if all you give in your issue is a call stack with no info for how to reproduce the issue or any code snippets, you can probably expect your issue will be closed.

**Comment by AstRonin** [comment]
You no need more information what I provided.
look on the function `printValue`. `this.el` is null when react removed it element.
node_modules/countup.js/dist/countUp.js
just need to add `if (this.el)` like you already have in a previous 1.9 version

**Comment by inorganik** [comment]
There is no code in CountUp.js that reads attributes. You are in the wrong place! I suggest you file a better quality issue that someone can actually debug in the countup react repo.

**Comment by AstRonin** [comment]
m... I mean this line
https://github.com/inorganik/countUp.js/blob/master/src/countUp.ts#L249

ok, as you suggest I will open ticket on react-countup

**Comment by inorganik** [comment]
Ok, I see where it reads tagName of the element. But the issue does belong on the react-countup repo. 

Also, just from the tiny bit of extra context you provided in the other issue (how hard was that?) I can tell you that all you need to do is use a component will unmount hook and either reset or delete the instance of countUp inside it. Not sure how that is done with the react countup component
