### ISSUE TITLE
Unable to display 0 as 00

### ISSUE THREAD

**Issue by jcsdesterke** [inorganik/countUp.js#322]
## Description
![image](https://github.com/inorganik/countUp.js/assets/58807486/7e9cddb5-bb08-453a-8194-b8ce316d4b65)

I want to be able to display 0 as 00 because I use two different countup elements because of the styling for it.

**Comment by inorganik** [comment]
The way to accomplish this is by having a single countUp element and to pass a custom formatting function. Here I just modify the formatting function that ships with CountUp so that it wraps the decimal in a `<sup>` tag (and remove some unnecessary stuff). Or you could use a span if you prefer:

```js

function customFormat(num) {
    let neg = (num < 0) ? '-' : '';
    let result, x1, x2;
    result = Math.abs(num).toFixed(2);
    result += '';
    let x = result.split('.');
    x1 = x[0];
    x2 = x.length > 1 ? ',' + x[1] : '';
    return neg + '€' + x1 + '<sup>' + x2 + '</sup>';
};

const countUp = new CountUp('targetId', 5234, {
  formattingFn: customFormat
});
```
