### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by hhsnopek** [inorganik/countUp.js#43]
When using component the name of the package corresponds with the name that you require. The current issue with the name of the package is that `countup.js` has a dot in it. Which doesn't follow the naming conventions for component. My suggestion is to change the name within `component.json` and `bower.json` so they correspond. I'm thinking the name should be `countup`

People will still be able to search for the package with the keywords and find this as easily as they did before, and we don't have to change the name of the repo; just the name defined in `component.json` and `bower.json` :grinning: 

example - TJ uses `page.js` as the name, but has the reference name as `page`:
[visionmedia/page](https://github.com/visionmedia/page.js)
`page = require('page');`

**Comment by inorganik** [comment]
Can you address this?

**Comment by hhsnopek** [comment]
see https://github.com/inorganik/countUp.js/issues/43
