### ISSUE TITLE
compiled coffee version doesn't work

### ISSUE THREAD

**Issue by inorganik** [inorganik/countUp.js#47]
Hey @HHSnopek could you look at this? The current compiled coffee version doesn't work. I compiled the coffee version from v1.1.2 and it didn't work either. 

Thanks!

**Comment by inorganik** [comment]
@hhsnopek do you want to redo the coffeescript version? If not that's cool, I'll close this issue.

**Comment by hhsnopek** [comment]
We shouldn't need this open anymore as realistically coffee users can still use our package and if they'd like to modify the source users should conform to owners style. You can close this out :grinning:
