### ISSUE TITLE
Not working with SVG text elements in Safari and IE

### ISSUE THREAD

**Issue by andrewnida** [inorganik/countUp.js#57]
I was using your library for some SVG and noticed it didn't work across all browsers. The "innerHTML" property doesn't exist on SVG text elements in Safari and IE. I swapped "innerHTML" for the "textContent" property and that seemed to fix it across all browsers. I didn't check across other use cases, but I didn't notice anything out of the ordinary where I was using it outside of SVG. Thanks for the library!

**Comment by davidbani** [comment]
@inorganik might be good for `tspan` element as well. Sorry to raise the issue again.
