### ISSUE TITLE
NewCap

### ISSUE THREAD

**Issue by marcobiedermann** [inorganik/countUp.js#61]
`var demo = new countUp`: A constructor name should start with an uppercase letter.

**Comment by inorganik** [comment]
I think you've got a point there but changing it would risk breaking a lot of people's code if Bower or Component pulls the latest version into their project. This is a style issue, and has nothing to do with the functionality of the code so I think I'll leave it as is unless a lot of people have a problem with it.

**Comment by marcobiedermann** [comment]
You are right. My problem is that JSHint marks this as warning. If you release it as a new major version it would be ok in my opinion.

**Comment by inorganik** [comment]
You could always fork this repo and format the code however you'd like....
