### ISSUE TITLE
Counter Freezes with console errors

### ISSUE THREAD

**Issue by digitalclover** [inorganik/countUp.js#65]
I'm currently using countUp.js for a long term counter (8 hour loop) for a kiosk display at a trade show.  The counter is only being display in the latest version of Google Chrome (Version 40.0.2214.115 64-bit) on a computer who's soul purpose is to display the counter and that's it.

I'm experiencing a issue where the counter freezes roughly 5 minutes into the count up.  The following console error is printed:
`Uncaught TypeError:`
`	undefined is not a function`
`	formatNumber`
`	printValue`
`	reset`
`	(anonymous function)`

Any clues as to what may be causing this, or is countUp.js not meant for longer term sessions like this?

My thanks in advance,
Joshua

**Comment by inorganik** [comment]
For what you are trying to do, countUp is the wrong solution. countUp is for single page visits and animations that last under a minute. If you want to display a time counter, like say a stopwatch or timer, you should use `setInterval` and have it update ever second. Example:

```js
setInterval(function() {
    // calculate time to display in counter based on current time, and counter start time.
}, 1000) 

```

If you want to give me more details about what you're trying to do, I can help you write it.

**Comment by digitalclover** [comment]
Thanks for the prompt response.  I was trying to save some time by finding an existing jQuery plug-in rather than writing custom script of my own.  I'll be fine with setting something up, but I appreciate your willingness.

Thanks again,
Joshua

**Comment by inorganik** [comment]
You sure? It would probably be super simple to write....
