### ISSUE TITLE
Multiple counters on the same page

### ISSUE THREAD

**Issue by julienstuder** [inorganik/countUp.js#66]
Hi !

it seems that we cannot run multiple counters on the same page, right ?
is there another way to achieve that ?

thanks for you answer and you plugin !

**Comment by inorganik** [comment]
You can have as many counters as you want. Please be specific about what problem you're running into - there is no reason why you can't have multiple counters on a page.

**Comment by inorganik** [comment]
Getting no response from the poster, going to close this until a specific issue is identified.

**Comment by julienstuder** [comment]
sorry about that, everything is ok, was an error on my side !

**Comment by raimie** [comment]
Hey Ignorik, 

I'd like to have 4 counters on a single page. 
When I only change the ID of the counter from 'demo' to 'demo1' to 'demo2', etc., it does not work. 
Can you please help me understand how to place multiple counters on a single page. 
Is there something I need to add more to the header?

**Comment by Jonathan-Hickey** [comment]
I have the same issue as raimie.

**Comment by inorganik** [comment]
Here's an example of multiple counters on a page. For each counter, you need to create a separate instance of `CountUp`:

```js
var demo1 = new CountUp("demo1Target", 0, 3882, 0, 2.5);
demo1.start()

var demo2 = new CountUp("demo2Target", 3882, 0, 0, 2.5);
demo2.start()

var demo3 = new CountUp("demo3Target", 98, 475, 0, 2.5);
demo3.start()
```
Notice how:
- each instance has a different target - "demo1Target", "demo2Target", etc
- each instance has `start()` called on it

http://jsfiddle.net/bcujgvf0/

**Comment by Jonathan-Hickey** [comment]
Hi Inorganik, 

Thanks for the quick reply. I was doing that... One small difference was that I was creating the CountUp instances on a response from a get request. 

I have moved the declarations outside the get, and the updates within response function.

Regards,
Jonathan

**Comment by stevenng** [comment]
Can we use HTML class names instead of IDs for the target?

**Comment by hasenov** [comment]
Hello inorganik, for example i've 5 list items with same class 
`
<li class="counter>555</li>
<li class="counter>555</li>
<li class="counter>555</li>
<li class="counter>555</li>
<li class="counter>555</li>
`
and i want them all to be animated with countUp.js, is it possible? i can't create unique id for each item, it's just not so conveniently
