### ISSUE TITLE
Publish to Bower & Npm

### ISSUE THREAD

**Issue by hhsnopek** [inorganik/countUp.js#73]
@inorganik all we need to do is publish to bower and npm.

## bower
Install bower `npm bower -g` verify the `bower.json` file then `bower register countup git@github.com/inorganik/countUp.js`

## npm
This will be a bit harder to do, I didn't realize that someone had taken the namescape `countup` on npm. Looking at that package though it hasn't been updated for a long time. There is a way to [disput namespaces on npm](https://www.npmjs.com/policies/disputes). Considering you're the author of countUp.js it makes sense for you to handle this (author to author).

**Comment by inorganik** [comment]
Will do. Thanks.

**Comment by tzd** [comment]
Please check countUp.js bower package (1.5.2)
When I try to install this package I got bower EMALFORMED error, it seems that you have fixed this in #74

**Comment by inorganik** [comment]
@hhsnopek - bower is already registered - but in your last commit you changed the name from "countUp.js" to "countup" - why? Is there a reason to register a duplicate?

@tzd thanks for letting us know, I made a new release which fixes the path in the bower file, which was broken. I just tested running "bower install countUp.js" and it worked. Try again and let us know if you have any problems... thanks.

**Comment by hhsnopek** [comment]
@inorganik I thought we both decided to change it in #43

**Comment by inorganik** [comment]
I guess I kind of rubber-stamped that one without thinking about it... Anyhow I changed it back.

**Comment by hhsnopek** [comment]
:+1: sounds good
