### ISSUE TITLE
Multiple countup shows console error 

### ISSUE THREAD

**Issue by marjss** [inorganik/countUp.js#78]
Am trying to make multiple countup on a single page and all the start and end values are same

so in this case is removed the line no: 152
if (!isNaN(self.endVal) && !isNaN(self.startVal) 
----> && self.startVal !== self.endVal 
                )

**Comment by inorganik** [comment]
What is your issue?

**Comment by inorganik** [comment]
Going to close this unless you can please clarify your issue... interested why you want to have a count up animation if the startVal and endVal are the same

**Comment by marjss** [comment]
Hey, I am developing a dashboard, in which multiple values are calculated dynamically and i use this plugin to show some effective anime to the user so that he can guess the calculation by counts, So my issue is when i use a single countup and set a start value "0" and end value to some variable, it works fine but when i use multiple countups on a single page with start value "0", and in some the end value will be "0" then the countup doesnt work on all the counts..

**Comment by inorganik** [comment]
Yeah, it's the condition you pointed out: `self.startVal !== self.endVal`.

I would suggest not initializing the countUp until you actually want it to count - because setting the startVal and endVal to the same number wouldn't animate anyway. Or you could remove that condition.
