### ISSUE TITLE
Easing with large numbers not working right

### ISSUE THREAD

**Issue by NSDrowned** [inorganik/countUp.js#80]
I'm trying to make it work with the number 61,450,980 and it seems to halt abruptly. 

I did some testing and I If I use a lower number (6000), it works perfectly. Tried with 60000 and it kind of worked but not perfect like with 6000. So it seem that with the way the slowing is calculated, the larger the number, the less easing it uses. Any idea how to fix this or am I doing something wrong?

**Comment by inorganik** [comment]
Yea... think about it. If you give it 3 seconds to animate from 0 to 61 million, it has a long way to go and a short time to do it, so it has to skip a lot of numbers. So it's working exactly as it should.

One option would be to set your `endVal` to 50 less than your actual `endVal`, then use the callback to call `update()` and set the `endVal` to your actual `endVal`. Like this:

```js
var demo = new CountUp('target', 0, 61450930, 0, 2);
demo.start(function() {
    demo.update(61450980)
});
```

http://jsfiddle.net/4d29w039/
