### ISSUE TITLE
Remove console.log from distribution build

### ISSUE THREAD

**Issue by justrhysism** [inorganik/countUp.js#82]
Console logging should only be for debugging - and it also breaks IE9.

**Comment by inorganik** [comment]
This is fixed in 1.6.

**Comment by daggmano** [comment]
Looks like the #1.6 version still has this issue.  Master is correct, but grabbing 1.6 over bower still exhibits this behaviour.  Could you tag a #1.7 version?

**Comment by inorganik** [comment]
Just tagged 1.6.1.

**Comment by daggmano** [comment]
Awesome!
