### ISSUE TITLE
Rounding decimal numbers

### ISSUE THREAD

**Issue by carylarcher** [inorganik/countUp.js#85]
I'm trying to include some decimal numbers in my counter but they keep rounding. For example, I entered 99.6 and it counts up to 100.

Is there anything in the settings I can change to stop this happening?

**Comment by inorganik** [comment]
You probably didn't read the README eh? Use the `decimals` param.

**Comment by carylarcher** [comment]
I was wondering if there was a way of having a mixture of decimal and whole numbers. So far all I've been able to do is have all to one decimal point or none.

**Comment by inorganik** [comment]
Mixture - can you elaborate?

**Comment by carylarcher** [comment]
For example, I have three stats showing up in a row. Say, 50%, 40%, 99.6%. The last one counts up to be 100% which I don't want. 

When I change the parameters to show one decimal point as expected all the numbers are changed. For example, 50.0%, 40.0%, 99.6%. I don't want this either! I want some numbers to one decimal place and some to be whole. I'm sorry if I'm barking up the wrong tree here.

**Comment by inorganik** [comment]
Seems like the obvious solution is to use a `0` for the `decimals` param on numbers you want whole, and  `1` for numbers you want a decimal. Am I missing something?

**Comment by carylarcher** [comment]
I've tried adding some javascript to check if the value has a "." in the string equivalent of the value  and have console.log(options) to check it is setting the right values here is the values of options that i have used but it still counts to 100
decimal: "."
decimals: 1
prefix: ""
separator: ","
suffix: ""
useEasing: true
useGrouping: true


here is the call to CountUp

var countUpElement = new CountUp($("span.value",this).get(0), 0, dataEndValue, 0, 2.5, options);

dataEndValue holds 99.6 according to console.log()

**Comment by IrishAdo** [comment]
We found the issue number of decimals is not supposed to be in the options object but the 3rd last parameter.
