### ISSUE TITLE
Start counting when it's in viewport

### ISSUE THREAD

**Issue by GeGeek** [inorganik/countUp.js#86]
Hi,

i have put my count in the bottom of my page, so we need to scroll to see it, the problem is when i scroll down, the counter is already finished, do you have a trick to start the count only when it's on viewport ?

Thanks !

**Comment by inorganik** [comment]
You're looking for scroll-spy - that's a separate lib. You can get one with Bootstrap, but I prefer to roll my own. You need a `window.onscroll` function that looks at the document offset and compares it with the offset of your countUp target element.

Here's an angular scroll spy module I wrote. You should be able to pick out the parts you need: https://gist.github.com/inorganik/cd6da5a79106d17b7c1b

**Comment by GeGeek** [comment]
Thanks, i found this : https://remysharp.com/2009/01/26/element-in-view-event-plugin it's working great :)

**Comment by IgorKurkov** [comment]
another solution for angular 8+ https://github.com/inorganik/ngx-countUp/issues/5#issuecomment-748490496
