### ISSUE TITLE
Delay countup function?

### ISSUE THREAD

**Issue by Awedbyacumen** [inorganik/countUp.js#87]
Hi Inorganik!

I've been searching the internet for a way to delay the countup command. I'm not really into Js, but I like your script and I'm using it on my website (http://crowdfunder.hu), it's a wordpress site.

For a reason, I want to delay the "100%"  countup, because it interfers with the logo animation (not good for user experience). Do you know a way to delay it for x (mili)seconds? I've seen some similar but less efficient scripts that has that function, but I want to stick to your script, because it's better.

Also, thank you for this great script, I'm sure many developers find it useful and an elegant sollution!

Cheers,

Attila

**Comment by inorganik** [comment]
Sure, in the `start()` function, just add a timeout:

```js
this.start = function(callback) {
        self.callback = callback;
        // make sure values are valid
        if (!isNaN(self.endVal) && !isNaN(self.startVal) && self.startVal !== self.endVal) {
            var delay = 1000; // 1 second
            setTimeout(function() {
                self.rAF = requestAnimationFrame(self.count);
            }, delay);
        } else {
            console.log('countUp error: startVal or endVal is not a number');
            self.printValue(endVal);
        }
        return false;
    };
```

This will delay all countUp animations. If you want to delay certain ones, do a check on the target.

**Comment by Awedbyacumen** [comment]
Okay, worked perfectly! Thank you very much :)
