### ISSUE TITLE
countUp error if startVal equals endVal

### ISSUE THREAD

**Issue by tscok** [inorganik/countUp.js#88]
When startVal equals endVal the console logs:
```
countUp error: startVal or endVal is not a number
```
Even if both values in fact are type number.

**Comment by inorganik** [comment]
This was fixed in 1.6.

**Comment by tscok** [comment]
Problem is the countUp.min.js file doesn't seem to have been affected by the updates in 1.6

**Comment by inorganik** [comment]
Thanks Mikael, I removed the extra minified file. The intention is to use the files in the dist/ folder.

**Comment by tscok** [comment]
Ok, thanks :+1:
