### ISSUE TITLE
What about npm installation ?

### ISSUE THREAD

**Issue by FlorentD** [inorganik/countUp.js#90]
Hello all !

I cannot find your amazing lib through npm. 
countUp and countup.js they seem to be from others repos.
Is there another name ?

Thanks !

**Comment by inorganik** [comment]
@hhsnopek ?

**Comment by hhsnopek** [comment]
looks like you never published it? https://gist.github.com/coolaj86/1318304

**Comment by Vivihung** [comment]
+1 publish to npm. 
Any plan?

**Comment by inorganik** [comment]
I contacted the person who owns the package "countup" on npm, @srk9. They aren't maintaining whatever they have there, so I'm hoping he'll let me use the name. As soon as I find out, I can hopefully get this resolved and publish it under "countup". Stay tuned...

**Comment by preco21** [comment]
+1
I hope solved well.

**Comment by srk9** [comment]
I looked into removing it but npm says its a bad idea because nobody will
be able to use the same name ever again. You can see this yourself by
trying to delete a project. If there is a work around please let me know, I
would like to help you if I can.
On Tue, Dec 22, 2015 at 1:24 PM Plusb Preco <notifications@github.com>
wrote:

> +1
> I hope solved well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inorganik/countUp.js/issues/90#issuecomment-166696458>
> .
>
-- 
Warmest Regards,

Dustin Gelegonya

**Comment by inorganik** [comment]
Thanks for the reply @skr9. Well I kind of screwed up because your repo is `countup`, another guy has `countup.js` which is the name in the package.json file. So now I have contacted him and if I can get that one, I can publish there and resolve this.

**Comment by inorganik** [comment]
Sorry for the long delay ..... I give you...... 

🎉 https://www.npmjs.com/package/countup 🎉

**Comment by Vivihung** [comment]
Yeah! Thanks for all the effort!!

**Comment by FlorentD** [comment]
Thank you !! :+1: :-)
